// <auto-generated />
using System;
using ClassroomAgent.ControlPlane.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomAgent.ControlPlane.Persistence.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260919091628_AddInstallationPushAddress")]
    partial class AddInstallationPushAddress
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomAgent.ControlPlane.Persistence.AllowedAdmin", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("AddedByOwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("added_by_owner_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid")
                        .HasColumnName("identifier");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_allowed_admin");

                    b.HasIndex("AddedByOwnerId")
                        .HasDatabaseName("ix_allowed_admin_added_by_owner_id");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("uq_allowed_admin_identifier");

                    b.HasIndex("InstallationId", "Email")
                        .IsUnique()
                        .HasDatabaseName("uq_allowed_admin_installation_email");

                    b.ToTable("allowed_admin", null, t =>
                        {
                            t.HasCheckConstraint("ck_allowed_admin_email_format", "char_length(email) BETWEEN 3 AND 254 AND email ~ '^[a-z0-9._''-]{1,64}@[a-z0-9.-]+$'");

                            t.HasCheckConstraint("ck_allowed_admin_email_lower", "email = lower(email)");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.ControlPlane.Persistence.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("RefusalCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("refusal_category");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_actor", "(actor_type = 'anonymous') = (actor_id IS NULL)");

                            t.HasCheckConstraint("ck_audit_event_actor_type", "actor_type IN ('owner', 'anonymous')");

                            t.HasCheckConstraint("ck_audit_event_outcome", "outcome IN ('succeeded', 'refused')");

                            t.HasCheckConstraint("ck_audit_event_refusal_category", "(outcome = 'refused') = (refusal_category IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_target", "(target_type IS NULL) = (target_id IS NULL)");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.ControlPlane.Persistence.Installation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<Guid>("Identifier")
                        .HasColumnType("uuid")
                        .HasColumnName("identifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PushAddress")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("push_address");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_installation");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("uq_installation_client_id");

                    b.HasIndex("Domain")
                        .IsUnique()
                        .HasDatabaseName("uq_installation_domain");

                    b.HasIndex("Identifier")
                        .IsUnique()
                        .HasDatabaseName("uq_installation_identifier");

                    b.ToTable("installation", null, t =>
                        {
                            t.HasCheckConstraint("ck_installation_client_id_format", "client_id ~ '^[0-9]{10,32}$'");

                            t.HasCheckConstraint("ck_installation_domain_format", "domain ~ '^[a-z0-9.-]{3,253}$' AND position('.' in domain) > 0");

                            t.HasCheckConstraint("ck_installation_domain_lower", "domain = lower(domain)");

                            t.HasCheckConstraint("ck_installation_name_length", "char_length(name) BETWEEN 1 AND 200");

                            t.HasCheckConstraint("ck_installation_push_address_format", "push_address IS NULL OR push_address ~ '^http://(\\[[0-9a-f:.]+\\]|[a-z0-9.-]{1,253}):[1-9][0-9]{0,4}$'");

                            t.HasCheckConstraint("ck_installation_status", "status IN ('active', 'suspended')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.ControlPlane.Persistence.InstanceLicenseCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("answered_at");

                    b.Property<string>("AnsweredCompatibility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("answered_compatibility");

                    b.Property<string>("AnsweredStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("answered_status");

                    b.Property<string>("ApplicationVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("application_version");

                    b.Property<int>("ContractVersion")
                        .HasColumnType("integer")
                        .HasColumnName("contract_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("InstallationId")
                        .HasColumnType("bigint")
                        .HasColumnName("installation_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_instance_license_check");

                    b.HasIndex("InstallationId")
                        .IsUnique()
                        .HasDatabaseName("uq_instance_license_check_installation_id");

                    b.ToTable("instance_license_check", null, t =>
                        {
                            t.HasCheckConstraint("ck_instance_license_check_answered_compatibility", "answered_compatibility IN ('supported', 'upgrade_recommended', 'upgrade_required')");

                            t.HasCheckConstraint("ck_instance_license_check_answered_status", "answered_status IN ('active', 'suspended')");

                            t.HasCheckConstraint("ck_instance_license_check_application_version", "application_version ~ '^(0|[1-9][0-9]{0,5})\\.(0|[1-9][0-9]{0,5})\\.(0|[1-9][0-9]{0,5})$'");

                            t.HasCheckConstraint("ck_instance_license_check_contract_version", "contract_version BETWEEN 1 AND 999999");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.ControlPlane.Persistence.Owner", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ui_language");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_owner");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("uq_owner_normalized_user_name");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_owner_singleton");

                    b.ToTable("owner", null, t =>
                        {
                            t.HasCheckConstraint("ck_owner_access_failed_count", "access_failed_count >= 0");

                            t.HasCheckConstraint("ck_owner_singleton", "singleton = true");

                            t.HasCheckConstraint("ck_owner_ui_language", "ui_language IN ('uk', 'en')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.ControlPlane.Persistence.AllowedAdmin", b =>
                {
                    b.HasOne("ClassroomAgent.ControlPlane.Persistence.Owner", null)
                        .WithMany()
                        .HasForeignKey("AddedByOwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allowed_admin_added_by_owner");

                    b.HasOne("ClassroomAgent.ControlPlane.Persistence.Installation", null)
                        .WithMany()
                        .HasForeignKey("InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_allowed_admin_installation");
                });

            modelBuilder.Entity("ClassroomAgent.ControlPlane.Persistence.InstanceLicenseCheck", b =>
                {
                    b.HasOne("ClassroomAgent.ControlPlane.Persistence.Installation", null)
                        .WithOne()
                        .HasForeignKey("ClassroomAgent.ControlPlane.Persistence.InstanceLicenseCheck", "InstallationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instance_license_check_installation");
                });
#pragma warning restore 612, 618
        }
    }
}
