// <auto-generated />
using System;
using ClassroomAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClassroomAgentDbContext))]
    [Migration("20261003194237_AddRetentionPurge")]
    partial class AddRetentionPurge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<DateTimeOffset?>("LastSuccessfulSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_sign_in_at");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PasswordIsTemporary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("password_is_temporary");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("SignInMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sign_in_method");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ui_language");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_app_user_normalized_email");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_access_failed_count", "access_failed_count >= 0");

                            t.HasCheckConstraint("ck_app_user_email_lowercase", "email = lower(email) AND normalized_email = lower(normalized_email)");

                            t.HasCheckConstraint("ck_app_user_password_hash", "(sign_in_method = 'password') = (password_hash IS NOT NULL)");

                            t.HasCheckConstraint("ck_app_user_password_temporary", "password_is_temporary = false OR sign_in_method = 'password'");

                            t.HasCheckConstraint("ck_app_user_role", "role IN ('admin', 'dean')");

                            t.HasCheckConstraint("ck_app_user_role_sign_in_method", "(role = 'admin') = (sign_in_method = 'google')");

                            t.HasCheckConstraint("ck_app_user_sign_in_method", "sign_in_method IN ('google', 'password')");

                            t.HasCheckConstraint("ck_app_user_ui_language", "ui_language IN ('uk', 'en')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_role");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<int?>("PurgedAccounts")
                        .HasColumnType("integer")
                        .HasColumnName("purged_accounts");

                    b.Property<int?>("PurgedAuditRows")
                        .HasColumnType("integer")
                        .HasColumnName("purged_audit_rows");

                    b.Property<int?>("PurgedCourses")
                        .HasColumnType("integer")
                        .HasColumnName("purged_courses");

                    b.Property<int?>("PurgedLeaverMemberships")
                        .HasColumnType("integer")
                        .HasColumnName("purged_leaver_memberships");

                    b.Property<int?>("PurgedParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("purged_participants");

                    b.Property<string>("RefusalCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("refusal_category");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_audit_event_occurred_at");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_action", "action IN ('admin_sign_in', 'workspace_connection_saved', 'access_check_run', 'dean_account_created', 'dean_account_disabled', 'dean_account_reenabled', 'dean_account_password_reset', 'dean_password_changed', 'dean_sign_in', 'retention_purge_run')");

                            t.HasCheckConstraint("ck_audit_event_actor_id", "(actor_type = 'app_user') = (actor_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_actor_role", "(actor_type = 'app_user') = (actor_role IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_actor_role_value", "actor_role IS NULL OR actor_role IN ('admin', 'dean')");

                            t.HasCheckConstraint("ck_audit_event_actor_type", "actor_type IN ('app_user', 'anonymous', 'system')");

                            t.HasCheckConstraint("ck_audit_event_immutable", "updated_at = created_at");

                            t.HasCheckConstraint("ck_audit_event_outcome", "outcome IN ('succeeded', 'refused')");

                            t.HasCheckConstraint("ck_audit_event_purge_actor", "action <> 'retention_purge_run' OR (actor_type = 'system' AND target_type IS NULL AND target_id IS NULL AND outcome = 'succeeded' AND request_id IS NULL)");

                            t.HasCheckConstraint("ck_audit_event_purge_counts", "(action = 'retention_purge_run') = (purged_courses IS NOT NULL AND purged_leaver_memberships IS NOT NULL AND purged_participants IS NOT NULL AND purged_accounts IS NOT NULL AND purged_audit_rows IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_purge_counts_absent", "action = 'retention_purge_run' OR (purged_courses IS NULL AND purged_leaver_memberships IS NULL AND purged_participants IS NULL AND purged_accounts IS NULL AND purged_audit_rows IS NULL)");

                            t.HasCheckConstraint("ck_audit_event_purge_counts_non_negative", "(purged_courses IS NULL OR purged_courses >= 0) AND (purged_leaver_memberships IS NULL OR purged_leaver_memberships >= 0) AND (purged_participants IS NULL OR purged_participants >= 0) AND (purged_accounts IS NULL OR purged_accounts >= 0) AND (purged_audit_rows IS NULL OR purged_audit_rows >= 0)");

                            t.HasCheckConstraint("ck_audit_event_refusal_category", "(outcome = 'refused') = (refusal_category IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_refusal_category_value", "refusal_category IS NULL OR refusal_category IN ('not_in_allowed_admin', 'control_plane_unavailable', 'unknown_installation', 'callback_failed', 'account_disabled', 'domain_mismatch', 'impersonation_domain_mismatch', 'domain_not_confirmed', 'read_only_mode', 'connection_not_usable', 'unknown_login', 'wrong_password', 'locked_out')");

                            t.HasCheckConstraint("ck_audit_event_target", "target_id IS NULL OR target_type IS NOT NULL");

                            t.HasCheckConstraint("ck_audit_event_target_type_value", "target_type IS NULL OR target_type IN ('workspace_connection', 'app_user')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.ClassroomParticipant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)")
                        .HasColumnName("full_name");

                    b.Property<string>("GoogleUserId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_classroom_participant");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_classroom_participant_email");

                    b.HasIndex("GoogleUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_classroom_participant_google_user_id");

                    b.ToTable("classroom_participant", (string)null);
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.Course", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AlternateLink")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("alternate_link");

                    b.Property<string>("CalendarId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("calendar_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<string>("Description")
                        .HasMaxLength(30000)
                        .HasColumnType("character varying(30000)")
                        .HasColumnName("description");

                    b.Property<string>("DescriptionHeading")
                        .HasMaxLength(3600)
                        .HasColumnType("character varying(3600)")
                        .HasColumnName("description_heading");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerGoogleId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("owner_google_id");

                    b.Property<string>("Room")
                        .HasMaxLength(650)
                        .HasColumnType("character varying(650)")
                        .HasColumnName("room");

                    b.Property<string>("Section")
                        .HasMaxLength(2800)
                        .HasColumnType("character varying(2800)")
                        .HasColumnName("section");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("course_state");

                    b.Property<string>("TeacherFolderId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("teacher_folder_id");

                    b.Property<string>("TeacherFolderTitle")
                        .HasMaxLength(750)
                        .HasColumnType("character varying(750)")
                        .HasColumnName("teacher_folder_title");

                    b.Property<DateTimeOffset?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_course");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("uq_course_google_id");

                    b.ToTable("course", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_course_state", "course_state IN ('active', 'archived', 'provisioned', 'declined', 'suspended')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.CourseMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<bool>("OnRoster")
                        .HasColumnType("boolean")
                        .HasColumnName("on_roster");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint")
                        .HasColumnName("participant_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_course_membership");

                    b.HasIndex("LastSeenAt")
                        .HasDatabaseName("ix_course_membership_off_roster_last_seen")
                        .HasFilter("on_roster = false");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_course_membership_participant_id");

                    b.HasIndex("CourseId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("uq_course_membership_course_participant");

                    b.HasIndex("CourseId", "FirstSeenAt", "LastSeenAt")
                        .HasDatabaseName("ix_course_membership_course_seen");

                    b.ToTable("course_membership", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_membership_role", "role IN ('teacher', 'student')");

                            t.HasCheckConstraint("ck_course_membership_seen_order", "last_seen_at >= first_seen_at");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.CourseWork", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CourseId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("CreationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_time");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_id");

                    b.Property<DateTimeOffset>("ItemDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("item_date");

                    b.Property<decimal?>("MaxPoints")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("max_points");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("resource");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_course_work");

                    b.HasIndex("CourseId", "ItemDate")
                        .HasDatabaseName("ix_course_work_course_item_date");

                    b.HasIndex("CourseId", "Resource", "GoogleId")
                        .IsUnique()
                        .HasDatabaseName("uq_course_work_course_resource_google_id");

                    b.ToTable("course_work", null, t =>
                        {
                            t.HasCheckConstraint("ck_course_work_material_has_no_grading", "resource <> 'course_work_material' OR (max_points IS NULL AND due_at IS NULL)");

                            t.HasCheckConstraint("ck_course_work_max_points_non_negative", "max_points IS NULL OR max_points >= 0");

                            t.HasCheckConstraint("ck_course_work_resource", "resource IN ('course_work', 'course_work_material')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.LegitimacyState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("compatibility");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("LastSuccessfulCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_check_at");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_legitimacy_state");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_legitimacy_state_singleton");

                    b.ToTable("legitimacy_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_legitimacy_state_client_id_format", "client_id ~ '^[0-9]{10,32}$'");

                            t.HasCheckConstraint("ck_legitimacy_state_compatibility", "compatibility IN ('supported', 'upgrade_recommended', 'upgrade_required')");

                            t.HasCheckConstraint("ck_legitimacy_state_domain_length", "char_length(domain) BETWEEN 3 AND 253");

                            t.HasCheckConstraint("ck_legitimacy_state_singleton", "singleton");

                            t.HasCheckConstraint("ck_legitimacy_state_status", "status IN ('active', 'suspended')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.Submission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AssignedGrade")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("assigned_grade");

                    b.Property<long>("CourseWorkId")
                        .HasColumnType("bigint")
                        .HasColumnName("course_work_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DraftGrade")
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("draft_grade");

                    b.Property<string>("GoogleId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("google_id");

                    b.Property<bool>("Late")
                        .HasColumnType("boolean")
                        .HasColumnName("late");

                    b.Property<long>("ParticipantId")
                        .HasColumnType("bigint")
                        .HasColumnName("participant_id");

                    b.Property<string>("RawState")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("raw_state");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset?>("TurnedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turned_in_at");

                    b.Property<DateTimeOffset?>("UpdateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_time");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_submission");

                    b.HasIndex("ParticipantId")
                        .HasDatabaseName("ix_submission_participant_id");

                    b.HasIndex("CourseWorkId", "GoogleId")
                        .IsUnique()
                        .HasDatabaseName("uq_submission_course_work_google_id");

                    b.HasIndex("CourseWorkId", "ParticipantId")
                        .HasDatabaseName("ix_submission_course_work_participant");

                    b.ToTable("submission", null, t =>
                        {
                            t.HasCheckConstraint("ck_submission_grades_non_negative", "(assigned_grade IS NULL OR assigned_grade >= 0) AND (draft_grade IS NULL OR draft_grade >= 0)");

                            t.HasCheckConstraint("ck_submission_raw_state", "(state = 'unrecognised') = (raw_state IS NOT NULL)");

                            t.HasCheckConstraint("ck_submission_state", "state IN ('new', 'created', 'turned_in', 'returned', 'reclaimed_by_student', 'student_edited_after_turn_in', 'unrecognised')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("LastError")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastSuccessfulRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_run_at");

                    b.Property<int>("ProcessedCount")
                        .HasColumnType("integer")
                        .HasColumnName("processed_count");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uuid")
                        .HasColumnName("run_id");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_sync_state");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_sync_state_singleton");

                    b.ToTable("sync_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_sync_state_counter", "processed_count >= 0");

                            t.HasCheckConstraint("ck_sync_state_error_length", "last_error IS NULL OR char_length(last_error) BETWEEN 1 AND 512");

                            t.HasCheckConstraint("ck_sync_state_finished_after_started", "finished_at IS NULL OR finished_at >= started_at");

                            t.HasCheckConstraint("ck_sync_state_singleton", "singleton");

                            t.HasCheckConstraint("ck_sync_state_status", "status IN ('running', 'completed', 'failed')");

                            t.HasCheckConstraint("ck_sync_state_terminal_fields", "(status = 'running' AND finished_at IS NULL AND last_error IS NULL)\nOR (status = 'completed' AND finished_at IS NOT NULL AND last_error IS NULL)\nOR (status = 'failed' AND finished_at IS NOT NULL AND last_error IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.WorkspaceConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<string>("ImpersonationUserEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("impersonation_user_email");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspace_connection");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_workspace_connection_singleton");

                    b.ToTable("workspace_connection", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_connection_domain_format", "domain ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'");

                            t.HasCheckConstraint("ck_workspace_connection_domain_length", "char_length(domain) BETWEEN 3 AND 253");

                            t.HasCheckConstraint("ck_workspace_connection_domain_lowercase", "domain = lower(domain)");

                            t.HasCheckConstraint("ck_workspace_connection_email_domain", "split_part(impersonation_user_email, '@', 2) = domain");

                            t.HasCheckConstraint("ck_workspace_connection_email_format", "impersonation_user_email ~ '^[^@[:space:]]+@[^@[:space:]]+$'");

                            t.HasCheckConstraint("ck_workspace_connection_email_length", "char_length(impersonation_user_email) BETWEEN 3 AND 254");

                            t.HasCheckConstraint("ck_workspace_connection_email_lowercase", "impersonation_user_email = lower(impersonation_user_email)");

                            t.HasCheckConstraint("ck_workspace_connection_singleton", "singleton");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.CourseMembership", b =>
                {
                    b.HasOne("ClassroomAgent.Domain.Entities.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_membership_course");

                    b.HasOne("ClassroomAgent.Domain.Entities.ClassroomParticipant", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_membership_classroom_participant");

                    b.Navigation("Course");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.CourseWork", b =>
                {
                    b.HasOne("ClassroomAgent.Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_course_work_course");
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.Submission", b =>
                {
                    b.HasOne("ClassroomAgent.Domain.Entities.CourseWork", null)
                        .WithMany()
                        .HasForeignKey("CourseWorkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_course_work");

                    b.HasOne("ClassroomAgent.Domain.Entities.ClassroomParticipant", null)
                        .WithMany()
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_classroom_participant");
                });
#pragma warning restore 612, 618
        }
    }
}
