// <auto-generated />
using System;
using ClassroomAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClassroomAgentDbContext))]
    [Migration("20260926195656_AddDeanAccounts")]
    partial class AddDeanAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDisabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_disabled");

                    b.Property<DateTimeOffset?>("LastSuccessfulSignInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_sign_in_at");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("password_hash");

                    b.Property<bool>("PasswordIsTemporary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("password_is_temporary");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("SignInMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("sign_in_method");

                    b.Property<string>("UiLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("ui_language");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("uq_app_user_normalized_email");

                    b.ToTable("app_user", null, t =>
                        {
                            t.HasCheckConstraint("ck_app_user_access_failed_count", "access_failed_count >= 0");

                            t.HasCheckConstraint("ck_app_user_email_lowercase", "email = lower(email) AND normalized_email = lower(normalized_email)");

                            t.HasCheckConstraint("ck_app_user_password_hash", "(sign_in_method = 'password') = (password_hash IS NOT NULL)");

                            t.HasCheckConstraint("ck_app_user_password_temporary", "password_is_temporary = false OR sign_in_method = 'password'");

                            t.HasCheckConstraint("ck_app_user_role", "role IN ('admin', 'dean')");

                            t.HasCheckConstraint("ck_app_user_role_sign_in_method", "(role = 'admin') = (sign_in_method = 'google')");

                            t.HasCheckConstraint("ck_app_user_sign_in_method", "sign_in_method IN ('google', 'password')");

                            t.HasCheckConstraint("ck_app_user_ui_language", "ui_language IN ('uk', 'en')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.AuditEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("action");

                    b.Property<long?>("ActorId")
                        .HasColumnType("bigint")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorRole")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_role");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("actor_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("outcome");

                    b.Property<string>("RefusalCategory")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("refusal_category");

                    b.Property<string>("RequestId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("request_id");

                    b.Property<long?>("TargetId")
                        .HasColumnType("bigint")
                        .HasColumnName("target_id");

                    b.Property<string>("TargetType")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("target_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_audit_event");

                    b.ToTable("audit_event", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_event_action", "action IN ('admin_sign_in', 'workspace_connection_saved', 'access_check_run', 'dean_account_created', 'dean_account_disabled', 'dean_account_reenabled', 'dean_account_password_reset', 'dean_password_changed', 'dean_sign_in')");

                            t.HasCheckConstraint("ck_audit_event_actor_id", "(actor_type = 'app_user') = (actor_id IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_actor_role", "(actor_type = 'app_user') = (actor_role IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_actor_role_value", "actor_role IS NULL OR actor_role IN ('admin', 'dean')");

                            t.HasCheckConstraint("ck_audit_event_actor_type", "actor_type IN ('app_user', 'anonymous', 'system')");

                            t.HasCheckConstraint("ck_audit_event_immutable", "updated_at = created_at");

                            t.HasCheckConstraint("ck_audit_event_outcome", "outcome IN ('succeeded', 'refused')");

                            t.HasCheckConstraint("ck_audit_event_refusal_category", "(outcome = 'refused') = (refusal_category IS NOT NULL)");

                            t.HasCheckConstraint("ck_audit_event_refusal_category_value", "refusal_category IS NULL OR refusal_category IN ('not_in_allowed_admin', 'control_plane_unavailable', 'unknown_installation', 'callback_failed', 'account_disabled', 'domain_mismatch', 'impersonation_domain_mismatch', 'domain_not_confirmed', 'read_only_mode', 'connection_not_usable', 'unknown_login', 'wrong_password', 'locked_out')");

                            t.HasCheckConstraint("ck_audit_event_target", "target_id IS NULL OR target_type IS NOT NULL");

                            t.HasCheckConstraint("ck_audit_event_target_type_value", "target_type IS NULL OR target_type IN ('workspace_connection', 'app_user')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.LegitimacyState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("compatibility");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("LastSuccessfulCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_check_at");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_legitimacy_state");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_legitimacy_state_singleton");

                    b.ToTable("legitimacy_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_legitimacy_state_client_id_format", "client_id ~ '^[0-9]{10,32}$'");

                            t.HasCheckConstraint("ck_legitimacy_state_compatibility", "compatibility IN ('supported', 'upgrade_recommended', 'upgrade_required')");

                            t.HasCheckConstraint("ck_legitimacy_state_domain_length", "char_length(domain) BETWEEN 3 AND 253");

                            t.HasCheckConstraint("ck_legitimacy_state_singleton", "singleton");

                            t.HasCheckConstraint("ck_legitimacy_state_status", "status IN ('active', 'suspended')");
                        });
                });

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.WorkspaceConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<string>("ImpersonationUserEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("impersonation_user_email");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_workspace_connection");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_workspace_connection_singleton");

                    b.ToTable("workspace_connection", null, t =>
                        {
                            t.HasCheckConstraint("ck_workspace_connection_domain_format", "domain ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'");

                            t.HasCheckConstraint("ck_workspace_connection_domain_length", "char_length(domain) BETWEEN 3 AND 253");

                            t.HasCheckConstraint("ck_workspace_connection_domain_lowercase", "domain = lower(domain)");

                            t.HasCheckConstraint("ck_workspace_connection_email_domain", "split_part(impersonation_user_email, '@', 2) = domain");

                            t.HasCheckConstraint("ck_workspace_connection_email_format", "impersonation_user_email ~ '^[^@[:space:]]+@[^@[:space:]]+$'");

                            t.HasCheckConstraint("ck_workspace_connection_email_length", "char_length(impersonation_user_email) BETWEEN 3 AND 254");

                            t.HasCheckConstraint("ck_workspace_connection_email_lowercase", "impersonation_user_email = lower(impersonation_user_email)");

                            t.HasCheckConstraint("ck_workspace_connection_singleton", "singleton");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
