// <auto-generated />
using System;
using ClassroomAgent.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClassroomAgent.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ClassroomAgentDbContext))]
    partial class ClassroomAgentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClassroomAgent.Domain.Entities.LegitimacyState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("client_id");

                    b.Property<string>("Compatibility")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("compatibility");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("LastSuccessfulCheckAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_successful_check_at");

                    b.Property<bool>("Singleton")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("singleton");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_legitimacy_state");

                    b.HasIndex("Singleton")
                        .IsUnique()
                        .HasDatabaseName("uq_legitimacy_state_singleton");

                    b.ToTable("legitimacy_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_legitimacy_state_client_id_format", "client_id ~ '^[0-9]{10,32}$'");

                            t.HasCheckConstraint("ck_legitimacy_state_compatibility", "compatibility IN ('supported', 'upgrade_recommended', 'upgrade_required')");

                            t.HasCheckConstraint("ck_legitimacy_state_domain_length", "char_length(domain) BETWEEN 3 AND 253");

                            t.HasCheckConstraint("ck_legitimacy_state_singleton", "singleton");

                            t.HasCheckConstraint("ck_legitimacy_state_status", "status IN ('active', 'suspended')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
